[workspace]
resolver = "2"
members = ["cms-core", "web"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[[workspace.metadata.leptos]]
name = "web"
bin-package = "web"
lib-package = "web"

site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "web/style/main.scss"

site-addr = "192.168.1.247:3005"
reload-port = 3006

bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
